### ISSUE TITLE
Document shiftwidth/softtabstop/tabstop caveat

### ISSUE THREAD

**Issue by itmecho** [nanotee/nvim-lua-guide#34]
I ran into an issue where the following settings weren't getting applied:
```
vim.bo.shiftwidth = 4
vim.bo.softtabstop = 0
vim.bo.tabstop = 4
```

They're in the neovim help as buffer options so I couldn't figure out why it wasn't working.

I happened to see a video on converting VimScript config to lua and he mentioned that you had to also set those options globally. After setting them on `vim.o`, they work. 

I tried removing them from `vim.bo` and just leaving the `vim.o` settings but this didn't work either. It seems that they have to be set in both places to work.

I don't know why this is (would love to know) but it might be good to at least document it here in case anyone else has this problem.

**Comment by nanotee** [comment]
This used to be documented on an older commit: https://github.com/nanotee/nvim-lua-guide/blob/f37a52e4e108d72eb0903376ec486b371ea1c689/README.md#caveats-3

I decided to delete it because I wasn't 100% confident this was the right explanation and I didn't want to accidentally spread misinformation. I can restore it if you think it's still useful

As a side note, there's a PR that adds `vim.opt` as a convenience wrapper around Vim options and behaves a lot like the `:set` command, but it hasn't been merged yet. It should make it much easier to configure Neovim in Lua

**Comment by itmecho** [comment]
Ah fair enough. Probably best not to if we're not sure on the reason behind it.

I'll keep an eye on that PR, thanks!

**Comment by matu3ba** [comment]
Is this merged [here](https://github.com/nanotee/nvim-lua-guide#using-meta-accessors) or what kind of explanations do you want to make? linking the issues?

**Comment by ibraheemdev** [comment]
I just spent half an hour figuring out why my tabstops and undo directory was not being set, and stumbled across this issue after fixing it by setting `vim.o` and `vim.bo` :cry: I think it would be very helpful to include some information about this, even if the reason isn't 100% known.

**Comment by nanotee** [comment]
You're right, this is useful information, at least until `vim.opt` lands in core. I've added some info in #55
