### ISSUE TITLE
Mention `debug.debug()`

### ISSUE THREAD

**Issue by runiq** [nanotee/nvim-lua-guide#5]
`debug.debug()` has [special handling in Neovim](https://gitter.im/neovim/neovim?at=5f3d4c01750a2741302d7288) and could be pretty useful to debug stuff.

**Comment by nanotee** [comment]
I had no idea this was a thing, let alone that you could use it in Neovim, this is neat! I actually haven't used the debug library in Lua before, I'd be interested in seeing how other developers use it in practice. I'll probably be playing with it to see if I can come up with some tips, thank you for bringing it to my attention

**Comment by nanotee** [comment]
Okay, so I've experimented a bit and `debug.debug()` isn't all that useful on its own since it doesn't have access to local variables. The [Programming in Lua](https://www.lua.org/pil/contents.html) book [explicitely says](https://www.lua.org/pil/23.html) that the debug library is not a full debugger but only a set of primitives you can use to write one.

I could get some interesting results by using `debug.sethook()` and `debug.getlocal()` in my own custom functions, but it's a lot of manual work. If anyone has any insights on how to use the debug library, your help would be more than appreciated.

For what it's worth, I've also tried to use a few LuaRocks packages for debugging and nvim either segfaults or glitches into oblivion...

**Comment by alerque** [comment]
My experience has been about the same. If anyone does come up with anything really useful I'm all ears.

**Comment by matu3ba** [comment]
Are you referring to `3.8 – The Debug Interface` ?
Bfredl has written [a debug console](https://github.com/bfredl/nvim-luadev), but I am unsure how complete it is.

**Comment by nanotee** [comment]
Someone wrote a debug adapter for Neovim (and it uses the debug library): [jbyuki/one-small-step-for-vimkind](https://github.com/jbyuki/one-small-step-for-vimkind)
I managed to get up and running fairly quickly using [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap). Both projects look really promising!

I'm going to close this issue and advertise these plugins in the guide. Feel free to reopen if needed!
