### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ellisonleao** [nanotee/nvim-lua-guide#9]
Hey @nanotee thanks for this awesome repository. It is certainly helping me on moving all my plugins and dotfiles to lua right now in neovim. I was wondering if you have any plans to make it available on other languages. I recently [started streaming](https://twitch.tv/npxbr) and i am planning to make that guide available in portuguese (my main language). Is this something you are interested for making it available here as well?

Thanks in advance!

**Comment by nanotee** [comment]
Thank you, I'm delighted to hear this repository is helpful to you! :)

I hadn't thought of making it available in other languages but I'd gladly accept translations! One potential problem is keeping translations up to date, as this guide is going to receive updates.

Would you rather keep the translation in a separate fork or make it available in this repository? I'd be fine with either choice, but a fork might be more convenient since you wouldn't have to wait for me to merge your changes

**Comment by ellisonleao** [comment]
Either way is fine, i already [did a fork](https://github.com/npxbr/nvim-lua-guide) and will be starting a new `README_pt-br.md`  file over there. Just let me know what you prefer.

**Comment by nanotee** [comment]
I guess for now it's simpler to just put a link to your repository so the translation can evolve independently, we can always merge it later

**Comment by ellisonleao** [comment]
sounds great
